name: Install libstdc++ headers
on: [push, workflow_dispatch]
jobs:
  install-headers:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt dist-upgrade -y && sudo apt install build-essential -y

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Git config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Download GCC source code
        uses: actions/checkout@v3
        with:
            repository: gcc-mirror/gcc
            path: gcc

      - name: Configure libstdc++
        run: |
          cd gcc/libstdc++-v3/
          mkdir build && cd build
          ../configure --enable-multilib=no --prefix=/ --enable-tls=no --enable-nls=no --disable-hosted-libstdcxx --disable-libstdcxx-verbose --enable-libstdcxx-threads=no --enable-libstdcxx-filesystem-ts=no --enable-libstdcxx-backtrace=no

      - name: Build libstdc++
        run: make -C gcc/libstdc++-v3/build/

      - name: Install libstdc++
        run: DESTDIR=$(pwd)/dest/ make -C gcc/libstdc++-v3/build/ install

      - name: Move headers
        run: rm -rf include && mv dest/include/c++/*/ include

      - name: Cleanup
        run: rm -rf gcc dest

      - name: Push
        run: |
          git config user.name 'ilobilo'
          git config user.email 'ilobilo@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ilobilo/libstdcxx-headers.git
          git fetch --all
          git add .
          git commit -m "Upload headers [ci skip]"
          git push origin master